ammamanager/urls.py
from django.urls import include, path

from .views import ammamanager, gyms, promotions

urlpatterns = [
    path('', ammamanager.home, name='home'),

    path('gyms/', include(([
        path('', gyms.gym_home, name='gym_home'),
        path('fighters/', gyms.ListFightersView.as_view(), name='fighter_list'),
        path('fighters/<int:pk>', gyms.fighter_view, name='fighter'),
        path('fighters/<int:pk>/<int:offer_pk>/accept', gyms.accept_fight, name='accept_fight'),
        path('fighters/<int:pk>/<int:offer_pk>/deny', gyms.deny_fight, name='deny_fight'),
        path('fighters/<int:pk>/delete', gyms.fighter_delete, name='fighter_delete'),
        path('fighters/<int:pk>/availability', gyms.fighter_availability, name='fighter_availability'),
        path('fighters/add/', gyms.FighterCreateView.as_view(), name='fighter_add'),
    ], 'ammamanager'), namespace='gyms')),


    path('promotions/', include(([
        path('', promotions.promotion_home, name='promotion_home'),
        path('events/', promotions.ListEventsView.as_view(), name='event_list'),
        path('events/add/', promotions.EventCreateView.as_view(), name='event_add'),
        path('events/<int:pk>/', promotions.event, name='event'),
        path('events/<int:pk>/finish', promotions.finish_event, name='finish_event'),
        path('events/<int:pk>/finished', promotions.finished_event, name='finished_event'),
        path('events/<int:pk>/bout/add', promotions.bout_add, name='bout_add'),
        path('events/<int:pk>/bout/<int:bout_pk>/', promotions.BoutView, name='bout'),
        path('events/<int:pk>/bout/<int:bout_pk>/finished/<int:fighter_pk>', promotions.finished_bout, name='finished_bout'),
        path('events/<int:pk>/bout/<int:bout_pk>/finished/draw', promotions.draw_bout, name='draw_bout'),
        path('events/<int:pk>/bout/<int:bout_pk>/finished/nc', promotions.nc_bout, name='nc_bout'),
        path('events/<int:pk>/bout/<int:bout_pk>/offer/<int:fighter_pk>', promotions.offer, name='offer'),
        path('events/<int:pk>/bout/<int:bout_pk>/removefighters', promotions.removeFighters, name='remove_fighters'),
        path('events/<int:pk>/bout/<int:bout_pk>/offerfight', promotions.offer_fight, name='offer_fight'),
    ], 'ammamanager'), namespace='promotions')),
]

project/urls.py
from django.urls import include, path
from django.contrib import admin
from ammamanager.views import ammamanager, gyms, promotions

urlpatterns = [
    path('', include('ammamanager.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', ammamanager.SignUpView.as_view(), name='signup'),
    path('accounts/signup/gym/', gyms.GymSignUpView.as_view(), name='gym_signup'),
    path('accounts/signup/promotion/', promotions.PromotionSignUpView.as_view(), name='promotion_signup'),
]

ammamanager/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import datetime
from django.utils.html import escape, mark_safe
from django.core.validators import MaxValueValidator


WEIGHT_CLASSES = (
    ('FLW', 'Flyweight'),
    ('BW', 'Bantamweight'),
    ('FW', 'Featherweight'),
    ('LW', 'Lightweight'),
    ('WW', 'Welterweight'),
    ('MW', 'Middleweight'),
    ('LHW', 'Light Heavyweight'),
    ('HW', 'Heavyweight'),
    ('WSW', 'Womens Strawweight'),
    ('WBW', 'Womens Bantamweight'),
    ('WFW', 'Womens Featherweight'),
)

METHODS = (
    ('KO', 'Knock out'),
    ('SUB', 'Submission'),
    ('DEC', 'Decision'),
    ('DRAW', 'Draw'),
    ('NC', 'No Contest'),
)


class User(AbstractUser):
    is_gym = models.BooleanField(default=False)
    is_promotion = models.BooleanField(default=False)


class Gym(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    #interests = models.ManyToManyField(Subject, related_name='interested_gyms')

    def __str__(self):
        return self.user.name


class Event(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='events')
    name = models.CharField(max_length=255)
    date = models.DateField(default=datetime.now())
    finished = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Fighter(models.Model):
    gym = models.ForeignKey(User, on_delete=models.CASCADE, related_name='fighters', null=True)
    fname = models.CharField(max_length=30)
    lname = models.CharField(max_length=30)
    nname = models.CharField(max_length=40)
    weight = models.CharField(max_length=4, choices=WEIGHT_CLASSES, default='FLW')
    wins = models.IntegerField(default=0)
    losses = models.IntegerField(default=0)
    draws = models.IntegerField(default=0)
    nc = models.IntegerField(default=0)
    points = models.IntegerField(default=1000)
    rank = models.IntegerField(default=0)
    available = models.BooleanField(default=True)
    createDate = models.DateField(default=datetime.now())
    initialPointsBoost = models.IntegerField(default=0)

    def __str__(self):
        return self.fname + " " + self.lname


class Bout(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='bouts')
    weight = models.CharField(max_length=4, choices=WEIGHT_CLASSES, default='FLW')
    fighter1 = models.ForeignKey(Fighter, on_delete=models.CASCADE, related_name='f1', blank=True, null=True)
    fighter2 = models.ForeignKey(Fighter, on_delete=models.CASCADE, related_name='f2', blank=True, null=True)
    accepted1 = models.BooleanField(default=False)
    accepted2 = models.BooleanField(default=False)
    set = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.weight


class FightOffer(models.Model):
    bout = models.ForeignKey(Bout,on_delete=models.CASCADE, related_name='bout')
    fighter = models.ForeignKey(Fighter, on_delete=models.CASCADE, related_name='offered_fighter')
    opponent = models.ForeignKey(Fighter, on_delete=models.CASCADE, related_name='opponent', blank=True, null=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='offer_event')
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return self.opponent


class FinishedFight(models.Model):
    bout = models.ForeignKey(Bout,on_delete=models.CASCADE, related_name='finishedbout')
    event = models.ForeignKey(Event,on_delete=models.CASCADE, related_name='finishedevent')
    winner = models.ForeignKey(Fighter, on_delete=models.CASCADE, related_name='winner')
    loser = models.ForeignKey(Fighter, on_delete=models.CASCADE, related_name='loser', default=None)
    method = models.CharField(max_length=5, choices=METHODS, default='DEC')
    round = models.IntegerField(default=1, validators=[MaxValueValidator(5)])
    min = models.IntegerField(default=1)
    sec = models.IntegerField(default=1)
    winnerPoints = models.IntegerField(default=0)
    loserPoints = models.IntegerField(default=0)

    def __str__(self):
        return self.winner

ammamanager/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError

from ammamanager.models import (Gym, User, Bout, FinishedFight)


class PromotionSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_promotion = True
        if commit:
            user.save()
        return user


class GymSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_gym = True
        user.save()
        gym = Gym.objects.create(user=user)
        return user


class BoutForm(forms.ModelForm):
    class Meta:
        model = Bout
        fields = ('weight',)


class FightForm(forms.ModelForm):
    class Meta:
        model = FinishedFight
        fields = ('method','round','min','sec',)

ammamanager/views/ammamanager.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from ..models import Fighter, FinishedFight
from django.db.models import Q


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def index(request):
    return render(request, 'index.html')


def home(request):
    if request.user.is_authenticated:
        if request.user.is_promotion:
            return redirect('promotions:promotion_home')
        else:
            return redirect('gyms:gym_home')
    return render(request, 'ammamanager/home.html')

ammamanager/views/gyms.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, TemplateView

from ..decorators import gym_required
from ..forms import GymSignUpForm
from ..models import Gym, User, Fighter, FightOffer, Bout, FinishedFight
from django.db.models import Q
import arrow


class GymSignUpView(CreateView):
    model = User
    form_class = GymSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'gym'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('gyms:gym_home')


@method_decorator([login_required, gym_required], name='dispatch')
class GymHomeView(TemplateView):
    template_name = 'ammamanager/gyms/gym_home.html'

    def get_context_data(self, **kwargs):
        context = super(GymHomeView, self).get_context_data(**kwargs)
        context['30_day_registrations'] = self.thirty_day_registrations()
        return context

    def thirty_day_registrations(self):
        final_data = []

        date = arrow.now()
        for day in range(1, 30):
            date = date.replace(days=-1)
            count = 5
            final_data.append(count)

        return final_data


@login_required
@gym_required
def gym_home(request,*args, **kwargs):
    fighters = Fighter.objects.all().filter(gym=request.user)
    fights = FinishedFight.objects.all().filter()
    ko = 0
    sub = 0
    dec = 0
    for w in fights:
        if w.winner in fighters:
            if w.method == 'KO':
                ko += 1
            elif w.method == 'SUB':
                sub += 1
            elif w.method == 'DEC':
                dec += 1

    lko = 0
    lsub = 0
    ldec = 0
    for w in fights:
        if w.loser in fighters:
            if w.method == 'KO':
                lko += 1
            elif w.method == 'SUB':
                lsub += 1
            elif w.method == 'DEC':
                ldec += 1

    offered = []
    for f in fighters:
        offers = FightOffer.objects.all().filter(Q(fighter=f) | Q(opponent=f))
        if offers:
            offered.append(f)

    #offered = list(dict.fromkeys(offered))


    return render(request, 'ammamanager/gyms/gym_home.html', {
        'KO' : ko,
        'SUB' : sub,
        'DEC' : dec,
        'lKO': lko,
        'lSUB': lsub,
        'lDEC': ldec,
        'offered': offered
    })


@method_decorator([login_required, gym_required], name='dispatch')
class ListFightersView(ListView):
    model = Fighter
    ordering = ('name', )
    context_object_name = 'fighters'
    template_name = 'ammamanager/gyms/fighter_list.html'

    def get_queryset(self):
        query =  self.request.GET.get("q", None)
        queryset = self.request.user.fighters
        if query is not None:
            queryset = queryset.filter(fname__icontains=query)
        return queryset



@method_decorator([login_required, gym_required], name='dispatch')
class FighterCreateView(CreateView):
    model = Fighter
    fields = ('fname', 'lname', 'nname', 'weight', 'wins', 'losses', 'draws', 'nc' )
    template_name = 'ammamanager/gyms/fighter_add_form.html'

    def form_valid(self, form):
        fighter = form.save(commit=False)
        fighter.gym = self.request.user
        fighter.initialPointsBoost = (20 * fighter.wins) - (20 * fighter.losses)
        fighter.save()
        messages.success(self.request, 'Fighter Successfully Added!!')
        return redirect('gyms:fighter_list')


@login_required
@gym_required
def fighter_view(request, pk, *args, **kwargs):

    fighter = get_object_or_404(Fighter, pk=pk, gym=request.user)
    offers = FightOffer.objects.all()
    offersfighters = offers.filter(fighter = fighter)
    offersopponents = offers.filter(opponent = fighter)
    offers = offersfighters | offersopponents
    pastfights = Bout.objects.all().filter(Q(fighter1=fighter) | Q(fighter2=fighter)).order_by('-id')[:1]
    finishedfights = FinishedFight.objects.all().filter(Q(winner=fighter) | Q(loser=fighter)).order_by('-id')
    return render(request, 'ammamanager/gyms/fighter.html', {
        'fighter' : fighter,
        'offers' : offers,
        'past' : pastfights,
        'finished' : finishedfights
    })


@login_required
@gym_required
def fighter_delete(request, pk):

    fighter = get_object_or_404(Fighter, pk=pk)
    fighter.gym = None
    fighter.available = False
    fighter.save()
    return redirect('gyms:fighter_list')


@login_required
@gym_required
def accept_fight(request, pk, offer_pk):
    fighter = get_object_or_404(Fighter, pk=pk)
    offer = get_object_or_404(FightOffer, pk=offer_pk)
    bout = offer.bout
    offer.accepted = True
    offer.save()

    if fighter == bout.fighter1:
        bout.accepted1 = True
    else:
        bout.accepted2 = True

    if bout.accepted1 == True and bout.accepted2 == True:
        bout.set = True
        offers = FightOffer.objects.all()

        offersfighters1 = offers.filter(fighter=bout.fighter1)
        offersopponents1 = offers.filter(opponent=bout.fighter2)
        offers1 = offersfighters1 | offersopponents1
        for o in offers1:
            if o is not offer:
                o.bout.delete();
            o.delete()

        offersfighters2 = offers.filter(fighter=bout.fighter2)
        offersopponents2 = offers.filter(opponent=bout.fighter1)
        offers1 = offersfighters2 | offersopponents2
        for o in offers1:
            if o is not offer:
                o.bout.delete();
            o.delete()

        bout.fighter1.available = False
        bout.fighter2.available = False
        bout.fighter1.save()
        bout.fighter2.save()

    bout.save()

    return redirect('gyms:fighter', pk)


@login_required
@gym_required
def deny_fight(request, pk, offer_pk):
    fighter = get_object_or_404(Fighter, pk=pk)
    offer = get_object_or_404(FightOffer, pk=offer_pk)
    bout = offer.bout
    offer.delete()
    bout.delete()

    return redirect('gyms:fighter', pk)


@login_required
@gym_required
def fighter_availability(request, pk):
    fighter = get_object_or_404(Fighter, pk=pk)
    if fighter.available == False:
        fighter.available = True
    else:
        fighter.available = False
    fighter.save()
    return redirect('gyms:fighter', pk)


def score_fighters():
    fighters = Fighter.objects.all()
    fights = FinishedFight.objects.all()
    for fighter in fighters:
        points = fighter.initialPointsBoost
        fights = FinishedFight.objects.all().filter(Q(winner=fighter) | Q(loser=fighter))
        for fight in fights:
            if fight.winner == fighter:
                points += fight.winnerPoints
            else:
                points += fight.loserPoints
        fighter.points = 1000 + points;

    return 0

ammamanager/templates/ammamanager/gyms/fighter.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main>
    <h1>{{ fighter.fname }} {{ fighter.lname }}{%if fighter.available is True%}
        <a href="{% url 'gyms:fighter_availability' fighter.pk %}" style="float: right;"
           class="btn btn-outline-secondary" role="button">Make Unavailable</a>
        {%else%}
        <a href="{% url 'gyms:fighter_availability' fighter.pk %}" style="float: right;"
           class="btn btn-outline-secondary" role="button">Make Available</a>
        {%endif%}<a href="{% url 'gyms:fighter_delete' fighter.pk %}" style="float: right;"
                    class="btn btn-outline-secondary" role="button">Delete Fighter</a></h1>
    <h3>{{ fighter.weight }}: {{ fighter.rank }}  Points: {{fighter.points}}</h3>


    {%if fighter.available is False%}

    {% for f in past %}
    {%if f.event.finished == False%}
    <h3>Upcoming Fight</h3>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Event</th>
            <th>Date</th>
            <th>Fight</th>
        </tr>
        </thead>
        <tbody>

        <tr>
            <td class="align-middle">{{ f.event.name }}</td>
            <td class="align-middle">{{ f.event.date }}</td>
            <td class="align-middle">{{ f.fighter1 }} vs {{ f.fighter2 }}</td>
        </tr>
        {% endif %}
        {% empty %}
        <tr>
            <td class="bg-light text-center font-italic" colspan="5">No Upcoming Fight</td>
        </tr>
        {% endfor %}
        {%endif%}
        </tbody>
    </table>
        {%if fighter.available is True%}
        <h3>Offers</h3>
        <table class="table table-striped">
        <thead>
        <tr>
            <th>Event</th>
            <th>Date</th>
            <th>Fight</th>

        </tr>
        </thead>

        {% for offer in offers %}
        <tbody>
        <tr>
            <td class="align-middle">{{ offer.event.name }}</td>
            <td class="align-middle">{{ offer.event.date }}</td>
            <td class="align-middle">{{ offer.bout.fighter1 }} vs {{ offer.bout.fighter2 }} <a
                    href="{% url 'gyms:accept_fight' fighter.pk offer.pk %}" class="btn btn-outline-secondary"
                    role="button">Accept</a><a href="{% url 'gyms:deny_fight' fighter.pk offer.pk %}"
                                               class="btn btn-outline-secondary" role="button">Deny</a></td>
        </tr>
        </tbody>
        {% empty %}
        <tbody>
        <tr>
            <td class="bg-light text-center font-italic" colspan="5">No offers</td>
        </tr>
        </tbody>
        {% endfor %}
        {%endif%}

    </table>
    <h3>Fights</h3>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th></th>
                <th>Opponent</th>
                <th>Event</th>
                <th>Method</th>
                <th>Round</th>
                <th>Time</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            {%for a in finished%}
            {%if a.winner == fighter%}
            <tr>
                {%if a.method == 'DRAW'%}
                <td>D</td>
                {%elif a.method == 'NC'%}
                <td>NC</td>
                {%else%}
                <td>W</td>
                {%endif%}
                <td>{{a.loser}}</td>
                <td>{{a.bout.event}}</td>
                <td>{{a.method}}</td>
                <td>{{a.round}}</td>
                <td>{{a.min}}:{{a.sec}}</td>
                <td>{{a.bout.event.date}}</td>
            </tr>
            {%else%}
            <tr>
                {%if a.method == 'DRAW'%}
                <td>D</td>
                {%elif a.method == 'NC'%}
                <td>NC</td>
                {%else%}
                <td>L</td>
                {%endif%}
                <td>{{a.winner}}</td>
                <td>{{a.bout.event}}</td>
                <td>{{a.method}}</td>
                <td>{{a.round}}</td>
                <td>{{a.min}}:{{a.sec}}</td>
                <td>{{a.bout.event.date}}</td>
            </tr>
            {%endif%}
            {% empty %}
            <tr>
                <td class="bg-light text-center font-italic" colspan="5">No Previous Fights</td>
            </tr>
            {%endfor%}
            </tbody>
        </table>
    </div>
</main>

{% endblock %}

ammamanager/templates/ammamanager/gyms/fighter_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<main>
    <h2 class="mb-3">Add a Fighter</h2>
    <div class="row">
        <div class="col-md-6 col-sm-8 col-12">
            <form method="post" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Save</button>
                <a href="{% url 'gyms:fighter_list' %}" class="btn btn-outline-secondary" role="button">Cancel</a>
            </form>
        </div>
    </div>
</main>
{% endblock %}

ammamanager/templates/ammamanager/gyms/fighter_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>MMA-Helper</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<main>

    <h4>{{user}} Fighters <a href="{% url 'gyms:fighter_add' %}" style="float: right;" class="btn btn-primary" role="button">Add Fighter</a></h4>
    <form method='GET' action='/gyms/fighters/'>
        <input type='text' name='q' placeholder='Search'>
    </form>
    <div class="asset-inner">
        <table class="table table-striped">
            <tr>
                <th>Name</th>
                <th>Nickname</th>
                <th>Weight</th>
                <th>Rank</th>
                <th>Wins</th>
                <th>Losses</th>
                <th>Draws</th>
                <th>NC</th>
            </tr>
            {% for fighter in fighters.all %}
            <tr>
                <td class="align-middle"><a href="{% url 'gyms:fighter' fighter.pk %}">{{ fighter.fname }}
                    {{fighter.lname}}</a></td>
                <td class="align-middle">{{ fighter.nname }}</td>
                <td class="align-middle">{{ fighter.weight }}</td>
                <td class="align-middle">{{ fighter.rank }}</td>
                <td class="align-middle">{{ fighter.wins }}</td>
                <td class="align-middle">{{ fighter.losses }}</td>
                <td class="align-middle">{{ fighter.draws }}</td>
                <td class="align-middle">{{ fighter.nc }}</td>

                <td class="text-right">
                </td>
            </tr>
            {% empty %}
            <tr>
                <td class="bg-light text-center font-italic" colspan="5">No fighters in the gym.</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</main>

</html>
{% endblock %}

ammamanager/templates/ammamanager/gyms/gym_home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <meta charset="utf-8"/>
    <title>Gym Home</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0-rc.1/Chart.js"></script>
</head>
<main style="padding-top: 50px;">
    <h1 style="text-align: center;">{{user}}</h1>
    {% if KO == 0 and SUB == 0 and DEC == 0 and lKO == 0 and lSUB == 0 and lDEC == 0 %}
    <h3>Currently no stats available</h3>
    {%else%}
    <div id="contain">
    <div style="float: left;" class="col-lg-6 col-sm-12">
        <h3 style="text-align: center;">Method of Wins</h3>
        <canvas id="myChart" width="500" height="150" style="float: left;"></canvas></div>
    <div style="float: right;" class="col-lg-6 col-sm-12">
        <h3 style="text-align: center;">Method of Losses</h3>
        <canvas id="myChart2" width="500" height="150" style="float: left;"></canvas></div>
    </div>
    {%endif%}
    <h3>Offers For: </h3>
    <ul>
        {%for o in offered %}
        <li><a href="{% url 'gyms:fighter' o.pk %}">{{o}}</a></li>
        {%empty%}
        <li>No fighters currently have offers</li>
        {%endfor%}
    </ul>
    <script>

        var ctx = document.getElementById("myChart").getContext('2d');
        var ctx2 = document.getElementById("myChart2").getContext('2d');

        var myChart = new Chart(ctx, {
          type: 'pie',
          data: {
            labels: ["KO/TKO", "Submission", "DEC"],
            datasets: [{
              backgroundColor: [
                "#FF5757",
                "#3498db",
                "#95a5a6",
              ],
              data: [{{KO}}, {{SUB}}, {{DEC}}]
            }]
          }
        });
        var myChart2 = new Chart(ctx2, {
          type: 'pie',
          data: {
            labels: ["KO/TKO", "Submission", "DEC"],
            datasets: [{
              backgroundColor: [
                "#FF5757",
                "#3498db",
                "#95a5a6",
              ],
              data: [{{lKO}}, {{lSUB}}, {{lDEC}}]
            }]
          }
        });
    </script>
</main>
{% endblock %}

ammamanager/templates/ammamanager/gyms/quiz_list.html
{% extends 'base.html' %}

{% block content %}
  {% include 'ammamanager/gyms/_header.html' with active='new' %}
  <div class="card">
    Gym Homepage
  </div>
  <a href="{% url 'gyms:fighter_list' %}" class="btn btn-primary mb-3" role="button">View Fighters</a>
{% endblock %}